export const templates = {
  cloud: [
    {
      name: 'Virtual Data Center',
      icon: 'Storage',
      description: 'Hosted virtual compute environment with configurable vCPU, RAM, and storage.',
      fieldSchema: [
        { name: 'location', label: 'Location', type: 'text', required: true },
        { name: 'vcpu', label: 'vCPU Count', type: 'number', required: true },
        { name: 'ramGb', label: 'RAM (GB)', type: 'number', required: true },
        { name: 'storageGb', label: 'Storage (GB)', type: 'number', required: true },
        {
          name: 'storageType',
          label: 'Storage Type',
          type: 'select',
          required: true,
          options: ['SSD', 'NVMe', 'HDD', 'Hybrid'],
        },
        { name: 'package', label: 'Package Name', type: 'text', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Disaster Recovery',
      icon: 'CloudSync',
      description: 'Off-site replication and failover environment for business continuity.',
      fieldSchema: [
        { name: 'sourceLocation', label: 'Source Location', type: 'text', required: true },
        { name: 'targetLocation', label: 'Target Location', type: 'text', required: true },
        { name: 'vmCount', label: 'VM Count', type: 'number', required: true },
        { name: 'storageGb', label: 'Storage (GB)', type: 'number', required: true },
        {
          name: 'rpo',
          label: 'RPO',
          type: 'select',
          required: true,
          options: ['15 min', '1 hour', '4 hours', '8 hours', '24 hours'],
        },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Backup',
      icon: 'Backup',
      description: 'Scheduled cloud backup service with configurable retention policies.',
      fieldSchema: [
        { name: 'storageGb', label: 'Storage (GB)', type: 'number', required: true },
        {
          name: 'frequency',
          label: 'Backup Frequency',
          type: 'select',
          required: true,
          options: ['Hourly', 'Daily', 'Weekly', 'Monthly'],
        },
        {
          name: 'retention',
          label: 'Retention Period',
          type: 'select',
          required: true,
          options: ['7 days', '14 days', '30 days', '90 days', '1 year'],
        },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Network Link',
      icon: 'Cable',
      description: 'Dedicated or shared network connectivity between sites.',
      fieldSchema: [
        {
          name: 'linkType',
          label: 'Link Type',
          type: 'select',
          required: true,
          options: ['MPLS', 'SD-WAN', 'Dedicated Fiber', 'VPN', 'Internet'],
        },
        { name: 'bandwidth', label: 'Bandwidth (Mbps)', type: 'number', required: true },
        { name: 'vlanId', label: 'VLAN ID', type: 'text', required: false },
        { name: 'provider', label: 'Provider', type: 'text', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Hardware',
      icon: 'Memory',
      description: 'Physical or virtual hardware assets under management.',
      fieldSchema: [
        {
          name: 'deviceType',
          label: 'Device Type',
          type: 'select',
          required: true,
          options: ['Server', 'Switch', 'Router', 'Firewall', 'Storage Array', 'UPS', 'Other'],
        },
        { name: 'vendor', label: 'Vendor', type: 'text', required: true },
        { name: 'model', label: 'Model', type: 'text', required: true },
        { name: 'serialNumber', label: 'Serial Number', type: 'text', required: false },
        { name: 'warrantyEnd', label: 'Warranty End Date', type: 'date', required: false },
        { name: 'purchaseCost', label: 'Purchase Cost', type: 'currency', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
  ],

  telecom: [
    {
      name: 'Voice Line',
      icon: 'Phone',
      description: 'Telephony lines including PRI, SIP trunk, and analog circuits.',
      fieldSchema: [
        {
          name: 'lineType',
          label: 'Line Type',
          type: 'select',
          required: true,
          options: ['SIP Trunk', 'PRI', 'Analog PSTN', 'VoIP', 'Mobile'],
        },
        { name: 'channels', label: 'Channel Count', type: 'number', required: true },
        { name: 'didNumbers', label: 'DID Numbers', type: 'text', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Data Circuit',
      icon: 'SettingsEthernet',
      description: 'Point-to-point or multipoint data circuits for site connectivity.',
      fieldSchema: [
        {
          name: 'circuitType',
          label: 'Circuit Type',
          type: 'select',
          required: true,
          options: ['MPLS', 'Metro Ethernet', 'Dark Fiber', 'DWDM', 'Leased Line'],
        },
        { name: 'bandwidth', label: 'Bandwidth (Mbps)', type: 'number', required: true },
        { name: 'circuitId', label: 'Circuit ID', type: 'text', required: false },
        { name: 'aEnd', label: 'A-End Location', type: 'text', required: true },
        { name: 'bEnd', label: 'B-End Location', type: 'text', required: true },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Internet Service',
      icon: 'Language',
      description: 'Broadband or dedicated internet access services.',
      fieldSchema: [
        {
          name: 'serviceType',
          label: 'Service Type',
          type: 'select',
          required: true,
          options: ['Dedicated Fiber', 'Cable', 'DSL', 'Fixed Wireless', '4G/LTE', '5G'],
        },
        { name: 'downloadSpeed', label: 'Download Speed (Mbps)', type: 'number', required: true },
        { name: 'uploadSpeed', label: 'Upload Speed (Mbps)', type: 'number', required: true },
        { name: 'ipAddresses', label: 'IP Address Block', type: 'text', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Equipment',
      icon: 'Router',
      description: 'Telecom CPE and network equipment provided to the customer.',
      fieldSchema: [
        {
          name: 'equipmentType',
          label: 'Equipment Type',
          type: 'select',
          required: true,
          options: ['Router', 'Switch', 'IP Phone', 'PBX', 'ONT', 'Media Gateway', 'Other'],
        },
        { name: 'model', label: 'Model', type: 'text', required: true },
        { name: 'serialNumber', label: 'Serial Number', type: 'text', required: false },
        {
          name: 'ownership',
          label: 'Ownership',
          type: 'select',
          required: true,
          options: ['Provider-owned', 'Customer-owned', 'Leased'],
        },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'SLA',
      icon: 'VerifiedUser',
      description: 'Service level agreement terms attached to a customer account.',
      fieldSchema: [
        {
          name: 'slaLevel',
          label: 'SLA Level',
          type: 'select',
          required: true,
          options: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Custom'],
        },
        { name: 'uptimeGuarantee', label: 'Uptime Guarantee (%)', type: 'number', required: true },
        {
          name: 'responseTime',
          label: 'Response Time',
          type: 'select',
          required: true,
          options: ['15 min', '30 min', '1 hour', '4 hours', 'Next business day'],
        },
        {
          name: 'resolutionTime',
          label: 'Resolution Time',
          type: 'select',
          required: true,
          options: ['2 hours', '4 hours', '8 hours', '24 hours', '48 hours'],
        },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
  ],

  msp: [
    {
      name: 'Managed Server',
      icon: 'DnsRounded',
      description: 'Fully managed physical or virtual server under MSP care.',
      fieldSchema: [
        {
          name: 'os',
          label: 'Operating System',
          type: 'select',
          required: true,
          options: ['Windows Server 2022', 'Windows Server 2019', 'Ubuntu 22.04', 'Ubuntu 20.04', 'RHEL 9', 'CentOS 8', 'Other'],
        },
        { name: 'vcpu', label: 'vCPU Count', type: 'number', required: true },
        { name: 'ramGb', label: 'RAM (GB)', type: 'number', required: true },
        { name: 'storageGb', label: 'Storage (GB)', type: 'number', required: true },
        { name: 'hostname', label: 'Hostname', type: 'text', required: true },
        { name: 'ipAddress', label: 'IP Address', type: 'text', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Endpoint Management',
      icon: 'Devices',
      description: 'Managed endpoint service covering desktops, laptops, and mobile devices.',
      fieldSchema: [
        { name: 'deviceCount', label: 'Device Count', type: 'number', required: true },
        {
          name: 'deviceType',
          label: 'Device Type',
          type: 'select',
          required: true,
          options: ['Windows PCs', 'Macs', 'Mixed Windows/Mac', 'Mobile Devices', 'Mixed All'],
        },
        { name: 'managementPlatform', label: 'Management Platform', type: 'text', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Security Service',
      icon: 'Security',
      description: 'Managed security offerings including SOC, EDR, and vulnerability management.',
      fieldSchema: [
        {
          name: 'serviceType',
          label: 'Service Type',
          type: 'select',
          required: true,
          options: ['SOC / SIEM', 'Endpoint Detection & Response', 'Vulnerability Management', 'Email Security', 'Firewall Management', 'Penetration Testing'],
        },
        { name: 'scope', label: 'Scope / Description', type: 'text', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'Backup',
      icon: 'Backup',
      description: 'Managed backup solution for servers, endpoints, and cloud workloads.',
      fieldSchema: [
        { name: 'storageGb', label: 'Storage (GB)', type: 'number', required: true },
        {
          name: 'frequency',
          label: 'Backup Frequency',
          type: 'select',
          required: true,
          options: ['Hourly', 'Daily', 'Weekly', 'Monthly'],
        },
        {
          name: 'retention',
          label: 'Retention Period',
          type: 'select',
          required: true,
          options: ['7 days', '14 days', '30 days', '90 days', '1 year'],
        },
        { name: 'offsite', label: 'Offsite Replication', type: 'boolean', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
    {
      name: 'License',
      icon: 'Key',
      description: 'Software license subscriptions managed on behalf of the customer.',
      fieldSchema: [
        { name: 'software', label: 'Software / Vendor', type: 'text', required: true },
        {
          name: 'licenseType',
          label: 'License Type',
          type: 'select',
          required: true,
          options: ['Per User', 'Per Device', 'Site License', 'Concurrent', 'OEM'],
        },
        { name: 'quantity', label: 'Quantity', type: 'number', required: true },
        { name: 'subscriptionId', label: 'Subscription / License ID', type: 'text', required: false },
        { name: 'renewalDate', label: 'Renewal Date', type: 'date', required: false },
        { name: 'mrc', label: 'Monthly Recurring Cost', type: 'currency', required: false },
      ],
    },
  ],
};
